name: Build nodejs app and push image to AWS ECR
on:
  # Trigger analysis when pushing in main or pull requests, and when creating 
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
    
    
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to AWS ECR
        id: login-ecr
        run: |
          docker login -u AWS -p $(aws ecr get-login-password --region ap-south-1)  public.ecr.aws/b3n7j6v1/hello
        env:
          TOKEN: ${{ secrets.TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 

      - name: Build and push Docker image
        run: |
          docker build -t hello .
          docker tag hello:latest public.ecr.aws/b3n7j6v1/hello:hello
          docker push public.ecr.aws/b3n7j6v1/hello:hello
