name: Build nodejs app and push image to AWS ECR
on:
  # Trigger analysis when pushing in main or pull requests, and when creating 
  push:
    branches:
    - main
  pull_request:
    branches:
    - test
    types: [opened, synchronize, reopened]
    
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to AWS ECR
        id: login-ecr
        run: |
         #docker login -u AWS -p $(aws ecr get-login-password --region ap-south-1)  934101640313.dkr.ecr.ap-south-1.amazonaws.com/mapup_assessment
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/w5a9d6i5
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 

      - name: Build and push Docker image
        run: |
          docker build -t hello_world .
          docker tag hello_world:latest 934101640313.dkr.ecr.ap-south-1.amazonaws.com/mapup_assessment:latest
          docker push 934101640313.dkr.ecr.ap-south-1.amazonaws.com/mapup_assessment:latest
